version: "1"
required_pr_gates:
  - workflow_file: "ci-pr-atomic.yml"
    workflow_name: "ci-pr-atomic"
    required_job_ids:
      - gate-profile
      - determinism
      - quality
      - build
      - smoke-wheel-matrix
      - tests-smoke
      - ssot
      - security
      - finalize
  - workflow_file: "workflow-integrity.yml"
    workflow_name: "Workflow Integrity"
    required_job_ids:
      - validate-workflows

  - workflow_file: "math-quality-gate.yml"
    workflow_name: "Math Quality Gate"
    required_job_ids:
      - math-gate

  - workflow_file: "dependency-review.yml"
    workflow_name: "dependency-review"
    required_job_ids:
      - dependency-review
