version: '1'
required_status_contexts:
- Math Quality Gate / math-gate
- Workflow Integrity / Validate workflow files
- ci-pr-atomic / build
- ci-pr-atomic / determinism
- ci-pr-atomic / finalize
- ci-pr-atomic / gate-profile
- ci-pr-atomic / quality
- ci-pr-atomic / security
- ci-pr-atomic / smoke-wheel-matrix (py3.11)
- ci-pr-atomic / smoke-wheel-matrix (py3.12)
- ci-pr-atomic / ssot
- ci-pr-atomic / tests-smoke
- dependency-review / dependency-review
- scientific-product-gate / scientific-product
