version: "1"
required_status_contexts:
  - "ci-pr-atomic / gate-profile"
  - "ci-pr-atomic / determinism"
  - "ci-pr-atomic / quality"
  - "ci-pr-atomic / build"
  - "ci-pr-atomic / smoke-wheel-matrix (py3.11)"
  - "ci-pr-atomic / smoke-wheel-matrix (py3.12)"
  - "ci-pr-atomic / tests-smoke"
  - "ci-pr-atomic / ssot"
  - "ci-pr-atomic / security"
  - "ci-pr-atomic / finalize"
  - "Workflow Integrity / Validate workflow files"
  - "Math Quality Gate / math-gate"
  - "dependency-review / dependency-review"
